<div id="site-navigation-display" class="btn-group">
  <button id="slide" class="button" title="Slider screen views" onclick="selectMarkdownDocument('slide');">Views</button>
  <button id="shell" class="button" title="Command Line usage" onclick="selectMarkdownDocument('shell')">Shell</button>
  <button id="repos" class="button" title="Similarity version release notes" onclick="selectMarkdownDocument('repos')">Releases</button>
  <button id="index" class="button" title="Similarity" onclick="selectMarkdownDocument('index')">Home</button>
  <img id="pin-navbar" class="pin-navbar" title="Toggle pin status" state="disabled" onclick="resetPinState();" src="https://ceresbakalite.github.io/similarity/images/NAVPinIconDisabled.png">
</div>
