<div class="slideshow-container">

  <!-- Full-width images with number and caption text -->
  <div class="mySlides fade">
    <div class="numbertext">1 / 7</div>
    <img src="https://ceresbakalite.github.io/similarity/images/slide/NAVScreenViews01.png" style="width:100%;">
    <div class="text">Caption Text</div>
  </div>

  <div class="mySlides fade">
    <div class="numbertext">2 / 7</div>
    <img src="https://ceresbakalite.github.io/similarity/images/slide/NAVScreenViews02.png" style="width:100%;">
    <div class="text">Caption Two</div>
  </div>

  <div class="mySlides fade">
    <div class="numbertext">3 / 7</div>
    <img src="https://ceresbakalite.github.io/similarity/images/slide/NAVScreenViews03.png" style="width:100%;">
    <div class="text">Caption Three</div>
  </div>

  <div class="mySlides fade">
    <div class="numbertext">4 / 7</div>
    <img src="https://ceresbakalite.github.io/similarity/images/slide/NAVScreenViews04.png" style="width:100%;">
    <div class="text">Caption Three</div>
  </div>

  <div class="mySlides fade">
    <div class="numbertext">5 / 7</div>
    <img src="https://ceresbakalite.github.io/similarity/images/slide/NAVScreenViews05.png" style="width:100%;">
    <div class="text">Caption Three</div>
  </div>

  <div class="mySlides fade">
    <div class="numbertext">6 / 7</div>
    <img src="https://ceresbakalite.github.io/similarity/images/slide/NAVScreenViews06.png" style="width:100%;">
    <div class="text">Caption Three</div>
  </div>

  <div class="mySlides fade">
    <div class="numbertext">7 / 7</div>
    <img src="https://ceresbakalite.github.io/similarity/images/slide/NAVScreenViews07.png" style="width:100%;">
    <div class="text">Caption Three</div>
  </div>

  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>

</div>

<br>

<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span>
  <span class="dot" onclick="currentSlide(2)"></span>
  <span class="dot" onclick="currentSlide(3)"></span>
  <span class="dot" onclick="currentSlide(4)"></span>
  <span class="dot" onclick="currentSlide(5)"></span>
  <span class="dot" onclick="currentSlide(6)"></span>
  <span class="dot" onclick="currentSlide(7)"></span>
</div>
