<div id="site-header-display" class="page-header section-header-background animate__animated animate__fadeInDown">
    <h1 class="project-name project-name-textcolor">Similarity</h1>
    <h2 class="project-tagline">Seeking patterns of similarity between data strings</h2>
    <a class="btn" href="https://github.com/ceresBakalite/similarity">View on GitHub</a>
    <a class="btn" target="_blank" rel="noreferrer" href="https://github.com/ceresBakalite/similarity/releases/tag/v1.3.5b">Download Similarity</a>
    <a href="https://github.com/ceresbakalite/similarity"><img style="position: absolute; top: 0; right: 0; border: 0; width:149px; height: 149px;" srcset="./images/GitHubForkMe_Right_Transparent.png 149w" src="./images/GitHubForkMe_Right_Transparent.png" alt="Fork me on GitHub"></a>
</div>
