<div id="site-header-display" style="z-index: 50" class="page-header section-header-background animate__animated animate__fadeInDown">
  <h1 class="project-name project-name-textcolor">Similarity</h1>
  <h2 class="project-tagline">Seeking patterns of similarity between data strings</h2>
  <a target="_blank" href="https://github.com/ceresBakalite/similarity" class="btn">View on GitHub</a>
  <a target="_blank" href="https://github.com/ceresBakalite/similarity/releases/tag/v1.3.5b" class="btn">Download Similarity</a>
  <a href="https://github.com/ceresbakalite"><img style="position: absolute; top: 0; right: 0; border: 0;" width="149" height="149" src="https://ceresbakalite.github.io/similarity/images/GitHubForkMe_Right_Transparent.png?resize=149%2C149" class="attachment-full size-full" alt="Fork me on GitHub" data-recalc-dims="1"></a>
</div>
