<div id="site-navigation-display" class="btn-group">
  <button class="button" title="Command Line usage" onclick="javascript:selectMarkdownDocument('shell')">Shell Notes</button>
  <button class="button" title="Similarity version release notes" onclick="javascript:selectMarkdownDocument('repos')">Release Notes</button>
  <button class="button" title="Similarity" onclick="javascript:selectMarkdownDocument('index')">Home</button>
</div>
