//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAVService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviations and Symbols.
        /// </summary>
        internal static string CAPTION_ABBREVIATIONS {
            get {
                return ResourceManager.GetString("CAPTION_ABBREVIATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity.
        /// </summary>
        internal static string CAPTION_APPLICATION {
            get {
                return ResourceManager.GetString("CAPTION_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity comparison.
        /// </summary>
        internal static string CAPTION_COMPARE {
            get {
                return ResourceManager.GetString("CAPTION_COMPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity comparison result.
        /// </summary>
        internal static string CAPTION_COMPARE_RESULT {
            get {
                return ResourceManager.GetString("CAPTION_COMPARE_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop.
        /// </summary>
        internal static string CAPTION_DRAG_DROP {
            get {
                return ResourceManager.GetString("CAPTION_DRAG_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove duplicates.
        /// </summary>
        internal static string CAPTION_DUPLCATE {
            get {
                return ResourceManager.GetString("CAPTION_DUPLCATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        internal static string CAPTION_EXIT_APPLICATION {
            get {
                return ResourceManager.GetString("CAPTION_EXIT_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisation Error.
        /// </summary>
        internal static string CAPTION_INITIALISATION_ERROR {
            get {
                return ResourceManager.GetString("CAPTION_INITIALISATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Workbook.
        /// </summary>
        internal static string CAPTION_OPEN_WORKBOOK {
            get {
                return ResourceManager.GetString("CAPTION_OPEN_WORKBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences and Views.
        /// </summary>
        internal static string CAPTION_PREFERENCES {
            get {
                return ResourceManager.GetString("CAPTION_PREFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Preference Error.
        /// </summary>
        internal static string CAPTION_PREFERENCES_ERROR {
            get {
                return ResourceManager.GetString("CAPTION_PREFERENCES_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Application.
        /// </summary>
        internal static string CAPTION_RESTART_APPLICATION {
            get {
                return ResourceManager.GetString("CAPTION_RESTART_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Workbook.
        /// </summary>
        internal static string CAPTION_SAVE_WORKBOOK {
            get {
                return ResourceManager.GetString("CAPTION_SAVE_WORKBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Patterns.
        /// </summary>
        internal static string CAPTION_SIMILARITY {
            get {
                return ResourceManager.GetString("CAPTION_SIMILARITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviations.
        /// </summary>
        internal static string CAPTION_TAB_ABBREVIATIONS {
            get {
                return ResourceManager.GetString("CAPTION_TAB_ABBREVIATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string CAPTION_TAB_EXPLORER {
            get {
                return ResourceManager.GetString("CAPTION_TAB_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string CAPTION_TAB_PREFERENCES {
            get {
                return ResourceManager.GetString("CAPTION_TAB_PREFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CONTROL_DELETEBUTTON_TEXT {
            get {
                return ResourceManager.GetString("CONTROL_DELETEBUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string CONTROL_NEWBUTTON_TEXT {
            get {
                return ResourceManager.GetString("CONTROL_NEWBUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Rows.
        /// </summary>
        internal static string CONTROL_REMOVEROWSBUTTON_TEXT {
            get {
                return ResourceManager.GetString("CONTROL_REMOVEROWSBUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore defaults.
        /// </summary>
        internal static string CONTROL_RESTOREBUTTON_TEXT {
            get {
                return ResourceManager.GetString("CONTROL_RESTOREBUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Worksheet.
        /// </summary>
        internal static string CONTROL_SEARCHBUTTON_TEXT {
            get {
                return ResourceManager.GetString("CONTROL_SEARCHBUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimilarityLogFile.txt.
        /// </summary>
        internal static string ERROR_LOG_FILENAME {
            get {
                return ResourceManager.GetString("ERROR_LOG_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string FIELD_VALUE_NO {
            get {
                return ResourceManager.GetString("FIELD_VALUE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string FIELD_VALUE_YES {
            get {
                return ResourceManager.GetString("FIELD_VALUE_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Workbook (*.xlsx)|*.xlsx|Excel 97-2003 Workbook (*.xls)|*.xls|Comma Separated Value (*.csv)|*.csv.
        /// </summary>
        internal static string FILE_OPENFILE_FILTER {
            get {
                return ResourceManager.GetString("FILE_OPENFILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Workbook (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string FILE_SAVEFILE_FILTER {
            get {
                return ResourceManager.GetString("FILE_SAVEFILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unrecoverable error occurred.  The abbreviations data binding failed on completion.
        /// </summary>
        internal static string NOTIFY_ABBREVIATION_BINDING {
            get {
                return ResourceManager.GetString("NOTIFY_ABBREVIATION_BINDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating a cell in the Abbreviations view.
        /// </summary>
        internal static string NOTIFY_ABBREVIATION_CELL {
            get {
                return ResourceManager.GetString("NOTIFY_ABBREVIATION_CELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! The word or phrase &quot;{0}&quot; requires an abbreviation or symbol.
        /// </summary>
        internal static string NOTIFY_ABBREVIATION_DATAGRIDVIEW {
            get {
                return ResourceManager.GetString("NOTIFY_ABBREVIATION_DATAGRIDVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when attempting to edit this abbreviation pair. The update failed to complete successfully.
        /// </summary>
        internal static string NOTIFY_ABBREVIATION_EDIT {
            get {
                return ResourceManager.GetString("NOTIFY_ABBREVIATION_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during startup. The abbreviations panel failed to initialise.
        /// </summary>
        internal static string NOTIFY_ABBREVIATION_FAIL {
            get {
                return ResourceManager.GetString("NOTIFY_ABBREVIATION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unrecoverable error occurred while attempting to apply abbreviations to the search criteria.  The parse command failed.{0}{0}The application is shutting down.
        /// </summary>
        internal static string NOTIFY_ABBREVIATION_FAILURE {
            get {
                return ResourceManager.GetString("NOTIFY_ABBREVIATION_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to create a word abbreviation pair.  The insert failed.
        /// </summary>
        internal static string NOTIFY_ABBREVIATION_INSERT {
            get {
                return ResourceManager.GetString("NOTIFY_ABBREVIATION_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to fetch the abbreviation type.  Unable to reach the database.
        /// </summary>
        internal static string NOTIFY_ABBREVIATION_TYPE {
            get {
                return ResourceManager.GetString("NOTIFY_ABBREVIATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can already make adjustments to this {1} abbreviation pair.{0}{0}The {2} &quot;{3}&quot; associated with the abbreviation &quot;{4}&quot; already exists and can be found in the {5} category.
        /// </summary>
        internal static string NOTIFY_ABBREVIATION_UPDATE {
            get {
                return ResourceManager.GetString("NOTIFY_ABBREVIATION_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialising abbreviations. This may take a few moments....
        /// </summary>
        internal static string NOTIFY_ABBREVIATIONPROGRESS {
            get {
                return ResourceManager.GetString("NOTIFY_ABBREVIATIONPROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU General Public License v3.0.
        /// </summary>
        internal static string NOTIFY_APPLICATION_LICENCE {
            get {
                return ResourceManager.GetString("NOTIFY_APPLICATION_LICENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string NOTIFY_APPLICATION_STARTING {
            get {
                return ResourceManager.GetString("NOTIFY_APPLICATION_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The commandline requires two arguments.{0}{0}{1} &quot;comparison string one&quot; &quot;comparison string two&quot;{0}{0}In addition the command line also supports the following arguments:{0}{0}MatchingAlgorithm (0,1,2){0}{0}Where:{0}   {5} = the {2} matching algorithm{0}   {6} = the {3} algorithm{0}   {7} = the {4} algorithm{0}{0}MakeCaseInsensitive (true or false){0}PadToEqualLength (true or false){0}RemoveWhitespace (true or false){0}ReverseComparison (true or false){0}PhoneticFilter (true or false){0}WholeWordCompariso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NOTIFY_COMMANDLINE_HELP {
            get {
                return ResourceManager.GetString("NOTIFY_COMMANDLINE_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{2} rows [{3}] excising {7} duplicates{0}Cumulative matching variations: c.{4}{0}{0}{5} matches found: {6}.
        /// </summary>
        internal static string NOTIFY_COMPARISON_RESULT {
            get {
                return ResourceManager.GetString("NOTIFY_COMPARISON_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Rows.
        /// </summary>
        internal static string NOTIFY_CURRENT_TOTAL {
            get {
                return ResourceManager.GetString("NOTIFY_CURRENT_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when preparing to delete word abbreviation pairs.
        /// </summary>
        internal static string NOTIFY_DELETE_ABBREVIATION {
            get {
                return ResourceManager.GetString("NOTIFY_DELETE_ABBREVIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this row?  This action cannot be undone.
        /// </summary>
        internal static string NOTIFY_DELETE_ROW {
            get {
                return ResourceManager.GetString("NOTIFY_DELETE_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to remove {1} rows from this workbook.{0}{0}Are you sure you wish to continue?  This action cannot be undone.
        /// </summary>
        internal static string NOTIFY_DELETE_ROWSCOUNT {
            get {
                return ResourceManager.GetString("NOTIFY_DELETE_ROWSCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete the selected rows?  This action cannot be undone.
        /// </summary>
        internal static string NOTIFY_DELETE_SELECTED_ROWS {
            get {
                return ResourceManager.GetString("NOTIFY_DELETE_SELECTED_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [Cancelling... ].
        /// </summary>
        internal static string NOTIFY_DISPLAYPROGRESS_CANCEL {
            get {
                return ResourceManager.GetString("NOTIFY_DISPLAYPROGRESS_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0}%  Processed {1} - {2} rows [{3}].
        /// </summary>
        internal static string NOTIFY_DISPLAYPROGRESS_PERCENTAGE {
            get {
                return ResourceManager.GetString("NOTIFY_DISPLAYPROGRESS_PERCENTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to leave the application?.
        /// </summary>
        internal static string NOTIFY_EXIT_APPLICATION {
            get {
                return ResourceManager.GetString("NOTIFY_EXIT_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields on this form are required fields.{0}{0}Please enter an abbreviation or symbol associated with the parent word or phrase..
        /// </summary>
        internal static string NOTIFY_FIELD_ABBREVIATION_ERROR {
            get {
                return ResourceManager.GetString("NOTIFY_FIELD_ABBREVIATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields on this form are required fields.{0}{0}Please enter a description of the word or phrase..
        /// </summary>
        internal static string NOTIFY_FIELD_DESCRIPTION_ERROR {
            get {
                return ResourceManager.GetString("NOTIFY_FIELD_DESCRIPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields on this form are required fields.{0}{0}Please enter a word or a phrase..
        /// </summary>
        internal static string NOTIFY_FIELD_ERROR {
            get {
                return ResourceManager.GetString("NOTIFY_FIELD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} is an unsupported file type.{0}{0}Supported file types are Excel Workbook(*.xlsx), Excel 97 - 2003 Workbook(*.xls) or Comma Separated Value(*.csv) files.
        /// </summary>
        internal static string NOTIFY_FILE_UNSUPPORTED {
            get {
                return ResourceManager.GetString("NOTIFY_FILE_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when attempting to open {1}{0}{0}The file is being used by another process.
        /// </summary>
        internal static string NOTIFY_FILEINUSE {
            get {
                return ResourceManager.GetString("NOTIFY_FILEINUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when attempting to open {1}{0}{0}The file could not be opened.
        /// </summary>
        internal static string NOTIFY_FILEOPEN_FAILED {
            get {
                return ResourceManager.GetString("NOTIFY_FILEOPEN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when attempting to save {0}.
        /// </summary>
        internal static string NOTIFY_FILESAVE_ERROR {
            get {
                return ResourceManager.GetString("NOTIFY_FILESAVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. An unexpected error has been encountered. This form will close.
        /// </summary>
        internal static string NOTIFY_FORM_ERROR {
            get {
                return ResourceManager.GetString("NOTIFY_FORM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress 0% - Analysing rows [{0}].
        /// </summary>
        internal static string NOTIFY_INITIALISE_DUPICATE_DISPLAY {
            get {
                return ResourceManager.GetString("NOTIFY_INITIALISE_DUPICATE_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: 0%.
        /// </summary>
        internal static string NOTIFY_INITIALISE_PROGRESS {
            get {
                return ResourceManager.GetString("NOTIFY_INITIALISE_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an unusually complex file to parse. Consider removing unnecessary columns or grouping data into smaller subsets.{0}{0}{1} rows{0}{2} columns{0}{3} duplicate rows{0}{0}Some data sets can take an inordinate length of time to process, particularly when they share few similarities{0}{0}.
        /// </summary>
        internal static string NOTIFY_LARGEFILE_WARNING {
            get {
                return ResourceManager.GetString("NOTIFY_LARGEFILE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial.
        /// </summary>
        internal static string NOTIFY_PARTIAL {
            get {
                return ResourceManager.GetString("NOTIFY_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an integer value.  This is a numeric field requiring an integer value between 0 and 100.
        /// </summary>
        internal static string NOTIFY_PERCENTAGE_VALIDATION {
            get {
                return ResourceManager.GetString("NOTIFY_PERCENTAGE_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential.
        /// </summary>
        internal static string NOTIFY_POTENTIAL {
            get {
                return ResourceManager.GetString("NOTIFY_POTENTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating a cell in the Preferences view.
        /// </summary>
        internal static string NOTIFY_PREFERENCE_CELL {
            get {
                return ResourceManager.GetString("NOTIFY_PREFERENCE_CELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference changes will take effect the next time the application is loaded.{0}{0}Would you like to restart the application now?.
        /// </summary>
        internal static string NOTIFY_PREFERENCE_CHANGES {
            get {
                return ResourceManager.GetString("NOTIFY_PREFERENCE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields on this form are required fields.{0}{0}This field represents:{0}{0}.
        /// </summary>
        internal static string NOTIFY_PREFERENCE_FIELDS {
            get {
                return ResourceManager.GetString("NOTIFY_PREFERENCE_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed: .
        /// </summary>
        internal static string NOTIFY_PROCESSED {
            get {
                return ResourceManager.GetString("NOTIFY_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.
        /// </summary>
        internal static string NOTIFY_PROGRESS_CANCELLED {
            get {
                return ResourceManager.GetString("NOTIFY_PROGRESS_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remainder: .
        /// </summary>
        internal static string NOTIFY_REMAINDER {
            get {
                return ResourceManager.GetString("NOTIFY_REMAINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore preferences to their defaults{0}{0}Are you sure you wish to continue?  This action cannot be undone.
        /// </summary>
        internal static string NOTIFY_RESTORE_PREFERENCES {
            get {
                return ResourceManager.GetString("NOTIFY_RESTORE_PREFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save changes to this Workbook?.
        /// </summary>
        internal static string NOTIFY_SAVEWORKBOOKCHANGES {
            get {
                return ResourceManager.GetString("NOTIFY_SAVEWORKBOOKCHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is about to close. Do you wish to save changes to this Workbook before closing and restarting the application?.
        /// </summary>
        internal static string NOTIFY_SAVEWORKBOOKCHANGES_ON_EXIT {
            get {
                return ResourceManager.GetString("NOTIFY_SAVEWORKBOOKCHANGES_ON_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to select one or more rows if you wish to delete words and their abbreviations.
        /// </summary>
        internal static string NOTIFY_SELECT_ABBREVIATION {
            get {
                return ResourceManager.GetString("NOTIFY_SELECT_ABBREVIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Release Version {1}.
        /// </summary>
        internal static string NOTIFY_SPLASHFORM_VERSION {
            get {
                return ResourceManager.GetString("NOTIFY_SPLASHFORM_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unrecoverable error has occurred during initialisation. The connection to the server has repeatedly timed out before a connection could be established.{0}{0}Unable to connect to the server. The application is shutting down.
        /// </summary>
        internal static string NOTIFY_SQLCONNECTION_ERROR {
            get {
                return ResourceManager.GetString("NOTIFY_SQLCONNECTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unrecoverable error has occurred during initialisation. The application is shutting down....
        /// </summary>
        internal static string NOTIFY_SQLINIITIALISATION_ERROR {
            get {
                return ResourceManager.GetString("NOTIFY_SQLINIITIALISATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unrecoverable error has occurred during initialisation. The error occurred when attempting to verify logon access.{0}{0}The application is shutting down.
        /// </summary>
        internal static string NOTIFY_SQLINIITIALISATION_LOGON_ERROR {
            get {
                return ResourceManager.GetString("NOTIFY_SQLINIITIALISATION_LOGON_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network connectivity appears to be unavailable.  A connection to the internet could not be established. The application is shutting down....
        /// </summary>
        internal static string NOTIFY_SQLNETWORK_UNAVAILABLE {
            get {
                return ResourceManager.GetString("NOTIFY_SQLNETWORK_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unrecoverable error has occurred. The server returned an invalid NULL reference.{0}{0}The application is shutting down....
        /// </summary>
        internal static string NOTIFY_SQLNULLREFERENCE_ERROR {
            get {
                return ResourceManager.GetString("NOTIFY_SQLNULLREFERENCE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred during the Squirrel.Windows update manager background process.{0}{0}The update manager has stopped..
        /// </summary>
        internal static string NOTIFY_SQUIRREL_UPDATE_ERROR {
            get {
                return ResourceManager.GetString("NOTIFY_SQUIRREL_UPDATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adjusting the &quot;{0}&quot; preference in the &quot;{1}&quot; category.  The category was not found.
        /// </summary>
        internal static string NOTIFY_UPDATE_PREFERENCE {
            get {
                return ResourceManager.GetString("NOTIFY_UPDATE_PREFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adjusting the &quot;{0}&quot; preference.  The preference was not found.
        /// </summary>
        internal static string NOTIFY_UPDATE_PREFERENCENAME {
            get {
                return ResourceManager.GetString("NOTIFY_UPDATE_PREFERENCENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The abbreviation definition.
        /// </summary>
        internal static string TOOLTIP_ABBREVIATIONDESCRIPTIONTEXT {
            get {
                return ResourceManager.GetString("TOOLTIP_ABBREVIATIONDESCRIPTIONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comparison search has been parsed for abbreviations and symbols.
        /// </summary>
        internal static string TOOLTIP_ABBREVIATIONLABEL {
            get {
                return ResourceManager.GetString("TOOLTIP_ABBREVIATIONLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short hand abbreviation used to represent the parent word or phrase.
        /// </summary>
        internal static string TOOLTIP_ABBREVIATIONTEXT {
            get {
                return ResourceManager.GetString("TOOLTIP_ABBREVIATIONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Excel Workbook (*.xlsx), Excel 97-2003 Workbook (*.xls) or Comma Separated Value (*.csv) file.
        /// </summary>
        internal static string TOOLTIP_ADDFILEBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_ADDFILEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this abbreviation when matching a word or phrase.
        /// </summary>
        internal static string TOOLTIP_ALWAYSUSETEXT {
            get {
                return ResourceManager.GetString("TOOLTIP_ALWAYSUSETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon the comparison pattern matching process.
        /// </summary>
        internal static string TOOLTIP_CANCELPROGRESSBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_CANCELPROGRESSBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage similarity returned when compared.
        /// </summary>
        internal static string TOOLTIP_COMPAREVALUETEXT {
            get {
                return ResourceManager.GetString("TOOLTIP_COMPAREVALUETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected rows.
        /// </summary>
        internal static string TOOLTIP_DELETEBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_DELETEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a row from the worksheet.
        /// </summary>
        internal static string TOOLTIP_DELETEROWFLAGTEXT {
            get {
                return ResourceManager.GetString("TOOLTIP_DELETEROWFLAGTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected rows from the worksheet within the specified range.
        /// </summary>
        internal static string TOOLTIP_DELETEWORKSHEETROWSBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_DELETEWORKSHEETROWSBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all work and exit the application.
        /// </summary>
        internal static string TOOLTIP_EXITBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_EXITBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information compared when matching similar items in the worksheet.
        /// </summary>
        internal static string TOOLTIP_EXPLORERSTRINGTEXT {
            get {
                return ResourceManager.GetString("TOOLTIP_EXPLORERSTRINGTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denotes the Parent or Child relationship.
        /// </summary>
        internal static string TOOLTIP_MATCHTYPETEXT {
            get {
                return ResourceManager.GetString("TOOLTIP_MATCHTYPETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new word abbreviation pair.
        /// </summary>
        internal static string TOOLTIP_NEWBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_NEWBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the Explorer, Preference and Abbreviation properties.
        /// </summary>
        internal static string TOOLTIP_PANELSLIDERPICTUREBOX {
            get {
                return ResourceManager.GetString("TOOLTIP_PANELSLIDERPICTUREBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find similarities, duplicates and cleanse the worksheet within the specified range.
        /// </summary>
        internal static string TOOLTIP_PARSEWORKSHEETBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_PARSEWORKSHEETBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore all preferences and views to their system defaults.
        /// </summary>
        internal static string TOOLTIP_RESTOREDEFAULTSBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_RESTOREDEFAULTSBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this file to an Excel Workbook (*.xlsx) file.
        /// </summary>
        internal static string TOOLTIP_SAVEWORKBOOKBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_SAVEWORKBOOKBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Worksheet.
        /// </summary>
        internal static string TOOLTIP_SHEETCOMBOBOX {
            get {
                return ResourceManager.GetString("TOOLTIP_SHEETCOMBOBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent word or phrase.
        /// </summary>
        internal static string TOOLTIP_WORDTEXT {
            get {
                return ResourceManager.GetString("TOOLTIP_WORDTEXT", resourceCulture);
            }
        }
    }
}
