//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61756A2B4C54496B3175624D5933774D7235394B514F3352562B6841622F41484A68514D46724F676" +
            "3356549793642713871556A4F37414B376A2B48624A453079714D505331502F5A34397246472B352" +
            "F73713951513D3D")]
        public string Target {
            get {
                return ((string)(this["Target"]));
            }
            set {
                this["Target"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACBA2BBDC5B11D634F754F1E8B149B1CD6C6AE10408AC98C8DA182560B7089A52C9AB4FA7383F53FB" +
            "88789A838B429879AB2BDF3C5F13805A9C3A436ACD34DC3")]
        public string HashKey {
            get {
                return ((string)(this["HashKey"]));
            }
            set {
                this["HashKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("384650384F587476376D344B5555712B38464234346C307175712B555363574F41474B314D614F597" +
            "758487A6A6C346B3235495A505543476D62627A5A50466668545937646676713968726D487A49797" +
            "1514C6579673D3D")]
        public string Signature {
            get {
                return ((string)(this["Signature"]));
            }
            set {
                this["Signature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sync {
            get {
                return ((bool)(this["Sync"]));
            }
            set {
                this["Sync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6A41702B3577365A7367765A656955626F52562B566C41556444597A3473566F4F714455736431786" +
            "D436173596C4B4876414B6B52776C4855654379647367702F726739714764473978717256316C4E7" +
            "A3442474F413D3D")]
        public string Update {
            get {
                return ((string)(this["Update"]));
            }
            set {
                this["Update"] = value;
            }
        }
    }
}
